export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST"
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS"
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL"


export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST"
export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS"
export const CATEGORY_DETAILS_FAILED =  "CATEGORY_DETAILS_FAILED"

export const CLEAR_ERRORS = "CLEAR_ERRORS";